default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

development:
  <<: *default
  database: todos_dev

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: <%= Rails.application.secrets.db_name %>
